// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using netcore.Data;
using netcore.Models.Invent;
using System;

namespace netcore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200329131848_updateprodLine111")]
    partial class updateprodLine111
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("netcore.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<bool>("ApplicationUserRole");

                    b.Property<bool>("BranchRole");

                    b.Property<bool>("CashRepositoryRole");

                    b.Property<bool>("CashflowInRole");

                    b.Property<bool>("CashflowOutRole");

                    b.Property<bool>("CatalogLineRole");

                    b.Property<bool>("CatalogRole");

                    b.Property<bool>("CategoryRole");

                    b.Property<bool>("CitiesRole");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<bool>("CustomerLineRole");

                    b.Property<bool>("CustomerRole");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("EmployeePaymentRole");

                    b.Property<bool>("EmployeeRole");

                    b.Property<bool>("HomeRole");

                    b.Property<bool>("InvoiceLineRole");

                    b.Property<bool>("InvoiceRole");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<bool>("MoneyTransferOrderRole");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<bool>("NumberSequenceRole");

                    b.Property<string>("PasswordHash");

                    b.Property<bool>("PaymentReceiveRole");

                    b.Property<bool>("PaymentTypeRole");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<bool>("ProductLineRole");

                    b.Property<bool>("ProductRole");

                    b.Property<bool>("PurchaseOrderLineRole");

                    b.Property<bool>("PurchaseOrderRole");

                    b.Property<bool>("ReceivingLineRole");

                    b.Property<bool>("ReceivingRole");

                    b.Property<bool>("SalesOrderLineRole");

                    b.Property<bool>("SalesOrderRole");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("ShipmentLineRole");

                    b.Property<bool>("ShipmentRole");

                    b.Property<bool>("StockRole");

                    b.Property<bool>("TransferInLineRole");

                    b.Property<bool>("TransferInRole");

                    b.Property<bool>("TransferOrderLineRole");

                    b.Property<bool>("TransferOrderRole");

                    b.Property<bool>("TransferOutLineRole");

                    b.Property<bool>("TransferOutRole");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<bool>("VendorCatalogLineRole");

                    b.Property<bool>("VendorCatalogRole");

                    b.Property<bool>("VendorLineRole");

                    b.Property<bool>("VendorPaymentRole");

                    b.Property<bool>("VendorRole");

                    b.Property<bool>("WarehouseRole");

                    b.Property<bool>("isSuperAdmin");

                    b.Property<string>("profilePictureUrl");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("netcore.Models.Invent.Branch", b =>
                {
                    b.Property<string>("branchId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("Fax")
                        .HasMaxLength(50);

                    b.Property<string>("OfficePhone")
                        .HasMaxLength(50);

                    b.Property<string>("PostalCode")
                        .HasMaxLength(50);

                    b.Property<string>("TaxOffice")
                        .HasMaxLength(50);

                    b.Property<string>("VATNumber")
                        .HasMaxLength(50);

                    b.Property<string>("branchName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("city")
                        .HasMaxLength(30);

                    b.Property<string>("country")
                        .HasMaxLength(30);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.Property<string>("email")
                        .HasMaxLength(50);

                    b.Property<bool>("isDefaultBranch");

                    b.Property<string>("province")
                        .HasMaxLength(30);

                    b.Property<string>("street1")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("branchId");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("netcore.Models.Invent.CashflowIn", b =>
                {
                    b.Property<string>("CashflowInId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("CashRepositoryFromCashRepositoryId");

                    b.Property<string>("CashRepositoryIdFrom")
                        .HasMaxLength(38);

                    b.Property<string>("CashRepositoryIdTo")
                        .HasMaxLength(38);

                    b.Property<string>("CashRepositoryToCashRepositoryId");

                    b.Property<DateTime>("CashflowInDate");

                    b.Property<string>("CashflowInNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("HasChild");

                    b.Property<string>("MoneyTransferOrderId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.HasKey("CashflowInId");

                    b.HasIndex("CashRepositoryFromCashRepositoryId");

                    b.HasIndex("CashRepositoryToCashRepositoryId");

                    b.HasIndex("MoneyTransferOrderId");

                    b.ToTable("CashflowIn");
                });

            modelBuilder.Entity("netcore.Models.Invent.CashflowOut", b =>
                {
                    b.Property<string>("CashflowOutId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("CashRepositoryFromCashRepositoryId");

                    b.Property<string>("CashRepositoryIdFrom")
                        .HasMaxLength(38);

                    b.Property<string>("CashRepositoryIdTo")
                        .HasMaxLength(38);

                    b.Property<string>("CashRepositoryToCashRepositoryId");

                    b.Property<DateTime>("CashflowOutDate");

                    b.Property<string>("CashflowOutNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("HasChild");

                    b.Property<string>("MoneyTransferOrderId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.HasKey("CashflowOutId");

                    b.HasIndex("CashRepositoryFromCashRepositoryId");

                    b.HasIndex("CashRepositoryToCashRepositoryId");

                    b.HasIndex("MoneyTransferOrderId");

                    b.ToTable("CashflowOut");
                });

            modelBuilder.Entity("netcore.Models.Invent.CashRepository", b =>
                {
                    b.Property<string>("CashRepositoryId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<decimal>("Balance");

                    b.Property<string>("CashRepositoryName")
                        .IsRequired();

                    b.Property<string>("Description");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(38);

                    b.Property<bool>("MainRepository");

                    b.Property<decimal>("TotalCashflowIn");

                    b.Property<decimal>("TotalCashflowOut");

                    b.Property<decimal>("TotalEmployeePayments");

                    b.Property<decimal>("TotalPayments");

                    b.Property<decimal>("TotalReceipts");

                    b.Property<DateTime>("createdAt");

                    b.HasKey("CashRepositoryId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("CashRepository");
                });

            modelBuilder.Entity("netcore.Models.Invent.Catalog", b =>
                {
                    b.Property<string>("CatalogId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("CatalogName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<DateTime>("createdAt");

                    b.HasKey("CatalogId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Catalog");
                });

            modelBuilder.Entity("netcore.Models.Invent.CatalogLine", b =>
                {
                    b.Property<string>("CatalogLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("CatalogId")
                        .HasMaxLength(38);

                    b.Property<decimal?>("Discount");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("ProductId")
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.HasKey("CatalogLineId");

                    b.HasIndex("CatalogId");

                    b.HasIndex("ProductId");

                    b.ToTable("CatalogLine");
                });

            modelBuilder.Entity("netcore.Models.Invent.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryName")
                        .IsRequired();

                    b.Property<int?>("ParentCategoryID");

                    b.HasKey("CategoryID");

                    b.HasIndex("ParentCategoryID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("netcore.Models.Invent.City", b =>
                {
                    b.Property<string>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<decimal>("ProductVAT");

                    b.Property<DateTime>("createdAt");

                    b.HasKey("CityId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("netcore.Models.Invent.Customer", b =>
                {
                    b.Property<string>("customerId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<bool>("Active");

                    b.Property<string>("CompanyActivity")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<decimal?>("OrderDiscount");

                    b.Property<bool>("SalesCount");

                    b.Property<decimal>("TaxDiscount");

                    b.Property<string>("TaxOffice")
                        .HasMaxLength(50);

                    b.Property<string>("VATRegNumber")
                        .HasMaxLength(50);

                    b.Property<string>("WebSite")
                        .HasMaxLength(50);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("customerName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.Property<string>("fax")
                        .HasMaxLength(20);

                    b.Property<string>("mobilePhone")
                        .HasMaxLength(20);

                    b.Property<string>("officePhone")
                        .HasMaxLength(20);

                    b.Property<int>("size");

                    b.Property<string>("workEmail")
                        .HasMaxLength(50);

                    b.HasKey("customerId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("netcore.Models.Invent.CustomerLine", b =>
                {
                    b.Property<string>("customerLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("LocLat")
                        .HasMaxLength(30);

                    b.Property<string>("LocLong")
                        .HasMaxLength(30);

                    b.Property<string>("PostCode")
                        .HasMaxLength(5);

                    b.Property<string>("ProductVAT");

                    b.Property<string>("city")
                        .HasMaxLength(30);

                    b.Property<string>("country")
                        .HasMaxLength(30);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("customerId")
                        .HasMaxLength(38);

                    b.Property<string>("province")
                        .HasMaxLength(30);

                    b.Property<string>("street1")
                        .HasMaxLength(50);

                    b.HasKey("customerLineId");

                    b.HasIndex("customerId");

                    b.ToTable("CustomerLine");
                });

            modelBuilder.Entity("netcore.Models.Invent.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<bool>("Active");

                    b.Property<decimal>("Commission");

                    b.Property<bool>("DefaultCarrier");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(50);

                    b.Property<decimal>("EmployeeBalance");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("PaymentReceiver");

                    b.Property<decimal>("Salary");

                    b.Property<decimal>("TotalCommission");

                    b.Property<decimal>("TotalEmployeePayment");

                    b.Property<decimal>("TotalSales");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("city")
                        .HasMaxLength(30);

                    b.Property<string>("country")
                        .HasMaxLength(30);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("fax");

                    b.Property<string>("mobilePhone");

                    b.Property<string>("officePhone");

                    b.Property<string>("personalEmail");

                    b.Property<string>("province")
                        .HasMaxLength(30);

                    b.Property<string>("street1")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("EmployeeId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("netcore.Models.Invent.EmployeePayment", b =>
                {
                    b.Property<string>("EmployeePaymentId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("CashRepositoryId")
                        .HasMaxLength(38);

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(38);

                    b.Property<decimal>("PaymentAmount");

                    b.Property<DateTime>("PaymentDate");

                    b.Property<string>("PaymentNumber");

                    b.Property<string>("PaymentTypeId")
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.HasKey("EmployeePaymentId");

                    b.HasIndex("CashRepositoryId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PaymentTypeId");

                    b.ToTable("EmployeePayment");
                });

            modelBuilder.Entity("netcore.Models.Invent.Invoice", b =>
                {
                    b.Property<string>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("Comments")
                        .HasMaxLength(100);

                    b.Property<string>("CustomerCity")
                        .HasMaxLength(30);

                    b.Property<string>("CustomerCompanyActivity")
                        .HasMaxLength(50);

                    b.Property<string>("CustomerCountry")
                        .HasMaxLength(30);

                    b.Property<string>("CustomerFax")
                        .HasMaxLength(20);

                    b.Property<string>("CustomerMobilePhone")
                        .HasMaxLength(20);

                    b.Property<string>("CustomerOfficePhone")
                        .HasMaxLength(20);

                    b.Property<string>("CustomerPostCode")
                        .HasMaxLength(5);

                    b.Property<string>("CustomerStreet")
                        .HasMaxLength(50);

                    b.Property<string>("CustomerTaxOffice")
                        .HasMaxLength(50);

                    b.Property<string>("CustomerVATRegNumber")
                        .HasMaxLength(50);

                    b.Property<string>("CustomerWorkEmail")
                        .HasMaxLength(50);

                    b.Property<string>("EmployeeName")
                        .HasMaxLength(30);

                    b.Property<string>("Fax")
                        .HasMaxLength(50);

                    b.Property<bool>("Finalized");

                    b.Property<string>("HasChild");

                    b.Property<decimal>("InvoiceBalance");

                    b.Property<DateTime>("InvoiceDate");

                    b.Property<string>("InvoiceNumber");

                    b.Property<string>("OfficePhone")
                        .HasMaxLength(50);

                    b.Property<bool>("Paid");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(50);

                    b.Property<string>("TaxOffice")
                        .HasMaxLength(50);

                    b.Property<decimal>("TotalBeforeDiscount");

                    b.Property<decimal>("TotalProductVAT");

                    b.Property<string>("VATNumber")
                        .HasMaxLength(50);

                    b.Property<string>("branchName")
                        .HasMaxLength(50);

                    b.Property<string>("city")
                        .HasMaxLength(30);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("customerName")
                        .HasMaxLength(50);

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.Property<string>("email")
                        .HasMaxLength(50);

                    b.Property<string>("shipmentId");

                    b.Property<string>("street1")
                        .HasMaxLength(50);

                    b.Property<decimal>("totalDiscountAmount");

                    b.Property<decimal>("totalOrderAmount");

                    b.Property<decimal>("totalPaymentReceive");

                    b.HasKey("InvoiceId");

                    b.HasIndex("shipmentId");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("netcore.Models.Invent.InvoiceLine", b =>
                {
                    b.Property<string>("InvoiceLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<decimal?>("Discount");

                    b.Property<decimal>("DiscountAmount");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<decimal>("Price");

                    b.Property<string>("ProductId")
                        .HasMaxLength(38);

                    b.Property<decimal>("ProductVAT");

                    b.Property<decimal>("ProductVATAmount");

                    b.Property<float>("Qty");

                    b.Property<decimal>("SpecialTaxAmount");

                    b.Property<decimal>("SpecialTaxDiscount");

                    b.Property<decimal?>("TotalAfterDiscount");

                    b.Property<decimal>("TotalAmount");

                    b.Property<decimal?>("TotalBeforeDiscount");

                    b.Property<decimal>("TotalSpecialTaxAmount");

                    b.Property<decimal>("TotalWithSpecialTax");

                    b.Property<decimal?>("UnitCost");

                    b.Property<DateTime>("createdAt");

                    b.HasKey("InvoiceLineId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductId");

                    b.ToTable("InvoiceLine");
                });

            modelBuilder.Entity("netcore.Models.Invent.MoneyTransferOrder", b =>
                {
                    b.Property<string>("MoneyTransferOrderId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("CashRepositoryFromCashRepositoryId");

                    b.Property<string>("CashRepositoryIdFrom")
                        .HasMaxLength(38);

                    b.Property<string>("CashRepositoryIdTo")
                        .HasMaxLength(38);

                    b.Property<string>("CashRepositoryToCashRepositoryId");

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.Property<string>("HasChild");

                    b.Property<DateTime>("MoneyTransferOrderDate");

                    b.Property<string>("MoneyTransferOrderNumber")
                        .HasMaxLength(20);

                    b.Property<int>("MoneyTransferOrderStatus");

                    b.Property<decimal>("PaymentAmount");

                    b.Property<DateTime>("createdAt");

                    b.Property<bool>("isIssued");

                    b.Property<bool>("isReceived");

                    b.HasKey("MoneyTransferOrderId");

                    b.HasIndex("CashRepositoryFromCashRepositoryId");

                    b.HasIndex("CashRepositoryToCashRepositoryId");

                    b.ToTable("MoneyTransferOrder");
                });

            modelBuilder.Entity("netcore.Models.Invent.NumberSequence", b =>
                {
                    b.Property<int>("NumberSequenceId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LastNumber");

                    b.Property<string>("Module")
                        .IsRequired();

                    b.Property<int>("MyProperty");

                    b.Property<string>("NumberSequenceName")
                        .IsRequired();

                    b.Property<string>("Prefix")
                        .IsRequired();

                    b.Property<DateTime>("createdAt");

                    b.HasKey("NumberSequenceId");

                    b.ToTable("NumberSequence");
                });

            modelBuilder.Entity("netcore.Models.Invent.PaymentReceive", b =>
                {
                    b.Property<string>("PaymentReceiveId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("CashRepositoryId")
                        .HasMaxLength(38);

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(38);

                    b.Property<string>("InvoiceId")
                        .HasMaxLength(38);

                    b.Property<bool>("IsFullPayment");

                    b.Property<decimal>("PaymentAmount");

                    b.Property<DateTime>("PaymentDate");

                    b.Property<string>("PaymentReceiveName");

                    b.Property<string>("PaymentTypeId")
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.HasKey("PaymentReceiveId");

                    b.HasIndex("CashRepositoryId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PaymentTypeId");

                    b.ToTable("PaymentReceive");
                });

            modelBuilder.Entity("netcore.Models.Invent.PaymentType", b =>
                {
                    b.Property<string>("PaymentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("Description");

                    b.Property<string>("PaymentTypeName")
                        .IsRequired();

                    b.Property<DateTime>("createdAt");

                    b.HasKey("PaymentTypeId");

                    b.ToTable("PaymentType");
                });

            modelBuilder.Entity("netcore.Models.Invent.Product", b =>
                {
                    b.Property<string>("productId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<bool>("Discontinued");

                    b.Property<string>("HasChild");

                    b.Property<decimal>("ProductVAT");

                    b.Property<decimal?>("ProductVolume");

                    b.Property<decimal?>("ProductWeight");

                    b.Property<int?>("ReorderLevel");

                    b.Property<decimal>("SpecialTaxValue");

                    b.Property<decimal?>("UnitCost");

                    b.Property<decimal?>("UnitPrice");

                    b.Property<string>("barcode")
                        .HasMaxLength(50);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.Property<string>("productCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("productType");

                    b.Property<string>("serialNumber")
                        .HasMaxLength(50);

                    b.Property<int>("uom");

                    b.HasKey("productId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("netcore.Models.Invent.ProductLine", b =>
                {
                    b.Property<string>("ProductLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("ComponentId")
                        .HasMaxLength(38);

                    b.Property<decimal>("Percentage");

                    b.Property<string>("ProductId")
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.HasKey("ProductLineId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductLine");
                });

            modelBuilder.Entity("netcore.Models.Invent.PurchaseOrder", b =>
                {
                    b.Property<string>("purchaseOrderId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<byte[]>("File");

                    b.Property<string>("HasChild");

                    b.Property<decimal>("InvoiceBalance");

                    b.Property<bool>("Paid");

                    b.Property<string>("branchId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<DateTime>("deliveryDate");

                    b.Property<string>("description")
                        .HasMaxLength(100);

                    b.Property<string>("picInternal")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("picVendor")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<DateTime>("poDate");

                    b.Property<string>("purchaseOrderNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("purchaseOrderStatus");

                    b.Property<string>("purchaseReceiveNumber");

                    b.Property<string>("referenceNumberExternal")
                        .HasMaxLength(30);

                    b.Property<int>("top");

                    b.Property<decimal>("totalDiscountAmount");

                    b.Property<decimal>("totalOrderAmount");

                    b.Property<decimal>("totalVendorPayment");

                    b.Property<string>("vendorId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.HasKey("purchaseOrderId");

                    b.HasIndex("branchId");

                    b.HasIndex("vendorId");

                    b.ToTable("PurchaseOrder");
                });

            modelBuilder.Entity("netcore.Models.Invent.PurchaseOrderLine", b =>
                {
                    b.Property<string>("purchaseOrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<decimal>("discountAmount");

                    b.Property<decimal>("price");

                    b.Property<string>("productId")
                        .HasMaxLength(38);

                    b.Property<string>("purchaseOrderId")
                        .HasMaxLength(38);

                    b.Property<float>("qty");

                    b.Property<decimal>("totalAmount");

                    b.HasKey("purchaseOrderLineId");

                    b.HasIndex("productId");

                    b.HasIndex("purchaseOrderId");

                    b.ToTable("PurchaseOrderLine");
                });

            modelBuilder.Entity("netcore.Models.Invent.Receiving", b =>
                {
                    b.Property<string>("receivingId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("branchId")
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("purchaseOrderId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<DateTime>("receivingDate");

                    b.Property<string>("receivingNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("vendorDO")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("vendorId")
                        .HasMaxLength(38);

                    b.Property<string>("vendorInvoice")
                        .HasMaxLength(50);

                    b.Property<string>("warehouseId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.HasKey("receivingId");

                    b.HasIndex("branchId");

                    b.HasIndex("purchaseOrderId");

                    b.HasIndex("vendorId");

                    b.HasIndex("warehouseId");

                    b.ToTable("Receiving");
                });

            modelBuilder.Entity("netcore.Models.Invent.ReceivingLine", b =>
                {
                    b.Property<string>("receivingLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("branchId")
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("productId")
                        .HasMaxLength(38);

                    b.Property<float>("qty");

                    b.Property<float>("qtyInventory");

                    b.Property<float>("qtyReceive");

                    b.Property<string>("receivingId")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseId")
                        .HasMaxLength(38);

                    b.HasKey("receivingLineId");

                    b.HasIndex("branchId");

                    b.HasIndex("productId");

                    b.HasIndex("receivingId");

                    b.HasIndex("warehouseId");

                    b.ToTable("ReceivingLine");
                });

            modelBuilder.Entity("netcore.Models.Invent.SalesOrder", b =>
                {
                    b.Property<string>("salesOrderId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<decimal>("Commission");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<bool>("Invoicing");

                    b.Property<string>("SalesOrderName");

                    b.Property<decimal>("TotalBeforeDiscount");

                    b.Property<decimal>("TotalProductVAT");

                    b.Property<decimal>("TotalWithSpecialTax");

                    b.Property<string>("branchId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("customerId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<string>("customerLineId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<DateTime>("deliveryDate");

                    b.Property<string>("description")
                        .HasMaxLength(100);

                    b.Property<string>("salesOrderNumber")
                        .HasMaxLength(20);

                    b.Property<int>("salesOrderStatus");

                    b.Property<string>("salesShipmentNumber");

                    b.Property<DateTime>("soDate");

                    b.Property<int>("top");

                    b.Property<decimal>("totalDiscountAmount");

                    b.Property<decimal>("totalOrderAmount");

                    b.HasKey("salesOrderId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("branchId");

                    b.HasIndex("customerId");

                    b.HasIndex("customerLineId");

                    b.ToTable("SalesOrder");
                });

            modelBuilder.Entity("netcore.Models.Invent.SalesOrderLine", b =>
                {
                    b.Property<string>("SalesOrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<decimal>("Discount");

                    b.Property<decimal>("DiscountAmount");

                    b.Property<decimal>("Price");

                    b.Property<string>("ProductId")
                        .HasMaxLength(38);

                    b.Property<decimal>("ProductVAT");

                    b.Property<decimal>("ProductVATAmount");

                    b.Property<float>("Qty");

                    b.Property<string>("SalesOrderId")
                        .HasMaxLength(38);

                    b.Property<decimal>("SpecialTaxAmount");

                    b.Property<decimal>("SpecialTaxDiscount");

                    b.Property<decimal>("TotalAfterDiscount");

                    b.Property<decimal>("TotalAmount");

                    b.Property<decimal>("TotalBeforeDiscount");

                    b.Property<decimal>("TotalSpecialTaxAmount");

                    b.Property<decimal>("TotalWithSpecialTax");

                    b.Property<decimal?>("UnitCost");

                    b.Property<DateTime>("createdAt");

                    b.HasKey("SalesOrderLineId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("SalesOrderLine");
                });

            modelBuilder.Entity("netcore.Models.Invent.Shipment", b =>
                {
                    b.Property<string>("shipmentId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("branchId")
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("customerId")
                        .HasMaxLength(38);

                    b.Property<string>("customerPO")
                        .HasMaxLength(50);

                    b.Property<int>("expeditionMode");

                    b.Property<int>("expeditionType");

                    b.Property<string>("invoiceNumber")
                        .HasMaxLength(50);

                    b.Property<string>("salesOrderId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<DateTime>("shipmentDate");

                    b.Property<string>("shipmentNumber")
                        .HasMaxLength(20);

                    b.Property<string>("warehouseId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.HasKey("shipmentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("branchId");

                    b.HasIndex("customerId");

                    b.HasIndex("salesOrderId");

                    b.HasIndex("warehouseId");

                    b.ToTable("Shipment");
                });

            modelBuilder.Entity("netcore.Models.Invent.ShipmentLine", b =>
                {
                    b.Property<string>("shipmentLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("branchId")
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("productId")
                        .HasMaxLength(38);

                    b.Property<float>("qty");

                    b.Property<float>("qtyInventory");

                    b.Property<float>("qtyShipment");

                    b.Property<string>("shipmentId")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseId")
                        .HasMaxLength(38);

                    b.HasKey("shipmentLineId");

                    b.HasIndex("branchId");

                    b.HasIndex("productId");

                    b.HasIndex("shipmentId");

                    b.HasIndex("warehouseId");

                    b.ToTable("ShipmentLine");
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferIn", b =>
                {
                    b.Property<string>("transferInId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("branchFrombranchId");

                    b.Property<string>("branchIdFrom")
                        .HasMaxLength(38);

                    b.Property<string>("branchIdTo")
                        .HasMaxLength(38);

                    b.Property<string>("branchTobranchId");

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("transferInDate");

                    b.Property<string>("transferInNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("transferOrderId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<string>("warehouseFromwarehouseId");

                    b.Property<string>("warehouseIdFrom")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseIdTo")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseTowarehouseId");

                    b.HasKey("transferInId");

                    b.HasIndex("branchFrombranchId");

                    b.HasIndex("branchTobranchId");

                    b.HasIndex("transferOrderId");

                    b.HasIndex("warehouseFromwarehouseId");

                    b.HasIndex("warehouseTowarehouseId");

                    b.ToTable("TransferIn");
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferInLine", b =>
                {
                    b.Property<string>("transferInLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("productId")
                        .HasMaxLength(38);

                    b.Property<float>("qty");

                    b.Property<float>("qtyInventory");

                    b.Property<string>("transferInId")
                        .HasMaxLength(38);

                    b.HasKey("transferInLineId");

                    b.HasIndex("productId");

                    b.HasIndex("transferInId");

                    b.ToTable("TransferInLine");
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferOrder", b =>
                {
                    b.Property<string>("transferOrderId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("branchFrombranchId");

                    b.Property<string>("branchIdFrom")
                        .HasMaxLength(38);

                    b.Property<string>("branchIdTo")
                        .HasMaxLength(38);

                    b.Property<string>("branchTobranchId");

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .HasMaxLength(100);

                    b.Property<bool>("isIssued");

                    b.Property<bool>("isReceived");

                    b.Property<string>("picName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("transferOrderDate");

                    b.Property<string>("transferOrderNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("transferOrderStatus");

                    b.Property<string>("warehouseFromwarehouseId");

                    b.Property<string>("warehouseIdFrom")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseIdTo")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseTowarehouseId");

                    b.HasKey("transferOrderId");

                    b.HasIndex("branchFrombranchId");

                    b.HasIndex("branchTobranchId");

                    b.HasIndex("warehouseFromwarehouseId");

                    b.HasIndex("warehouseTowarehouseId");

                    b.ToTable("TransferOrder");
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferOrderLine", b =>
                {
                    b.Property<string>("transferOrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("productId")
                        .HasMaxLength(38);

                    b.Property<float>("qty");

                    b.Property<string>("transferOrderId")
                        .HasMaxLength(38);

                    b.HasKey("transferOrderLineId");

                    b.HasIndex("productId");

                    b.HasIndex("transferOrderId");

                    b.ToTable("TransferOrderLine");
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferOut", b =>
                {
                    b.Property<string>("transferOutId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("branchFrombranchId");

                    b.Property<string>("branchIdFrom")
                        .HasMaxLength(38);

                    b.Property<string>("branchIdTo")
                        .HasMaxLength(38);

                    b.Property<string>("branchTobranchId");

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("transferOrderId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<DateTime>("transferOutDate");

                    b.Property<string>("transferOutNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("warehouseFromwarehouseId");

                    b.Property<string>("warehouseIdFrom")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseIdTo")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseTowarehouseId");

                    b.HasKey("transferOutId");

                    b.HasIndex("branchFrombranchId");

                    b.HasIndex("branchTobranchId");

                    b.HasIndex("transferOrderId");

                    b.HasIndex("warehouseFromwarehouseId");

                    b.HasIndex("warehouseTowarehouseId");

                    b.ToTable("TransferOut");
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferOutLine", b =>
                {
                    b.Property<string>("transferOutLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("productId")
                        .HasMaxLength(38);

                    b.Property<float>("qty");

                    b.Property<float>("qtyInventory");

                    b.Property<string>("transferOutId")
                        .HasMaxLength(38);

                    b.HasKey("transferOutLineId");

                    b.HasIndex("productId");

                    b.HasIndex("transferOutId");

                    b.ToTable("TransferOutLine");
                });

            modelBuilder.Entity("netcore.Models.Invent.Vendor", b =>
                {
                    b.Property<string>("vendorId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("PostCode")
                        .HasMaxLength(6);

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(15);

                    b.Property<string>("TaxOffice")
                        .HasMaxLength(50);

                    b.Property<string>("WebSite")
                        .HasMaxLength(100);

                    b.Property<string>("city")
                        .HasMaxLength(30);

                    b.Property<string>("country")
                        .HasMaxLength(30);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.Property<string>("fax");

                    b.Property<string>("mobilePhone");

                    b.Property<string>("officePhone");

                    b.Property<string>("personalEmail");

                    b.Property<string>("province")
                        .HasMaxLength(30);

                    b.Property<int>("size");

                    b.Property<string>("street1")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("vendorName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("workEmail");

                    b.HasKey("vendorId");

                    b.ToTable("Vendor");
                });

            modelBuilder.Entity("netcore.Models.Invent.VendorCatalog", b =>
                {
                    b.Property<string>("VendorCatalogId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("VendorCatalogName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.HasKey("VendorCatalogId");

                    b.HasIndex("VendorId");

                    b.ToTable("VendorCatalog");
                });

            modelBuilder.Entity("netcore.Models.Invent.VendorCatalogLine", b =>
                {
                    b.Property<string>("VendorCatalogLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<decimal?>("Discount");

                    b.Property<DateTime>("EndDate");

                    b.Property<decimal>("Price");

                    b.Property<string>("ProductId")
                        .HasMaxLength(38);

                    b.Property<string>("VendorCatalogId")
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.HasKey("VendorCatalogLineId");

                    b.HasIndex("ProductId");

                    b.HasIndex("VendorCatalogId");

                    b.ToTable("VendorCatalogLine");
                });

            modelBuilder.Entity("netcore.Models.Invent.VendorLine", b =>
                {
                    b.Property<string>("vendorLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("fax")
                        .HasMaxLength(20);

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("gender");

                    b.Property<string>("jobTitle")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("middleName")
                        .HasMaxLength(20);

                    b.Property<string>("mobilePhone")
                        .HasMaxLength(20);

                    b.Property<string>("nickName")
                        .HasMaxLength(20);

                    b.Property<string>("officePhone")
                        .HasMaxLength(20);

                    b.Property<string>("personalEmail")
                        .HasMaxLength(50);

                    b.Property<int>("salutation");

                    b.Property<string>("vendorId")
                        .HasMaxLength(38);

                    b.Property<string>("workEmail")
                        .HasMaxLength(50);

                    b.HasKey("vendorLineId");

                    b.HasIndex("vendorId");

                    b.ToTable("VendorLine");
                });

            modelBuilder.Entity("netcore.Models.Invent.VendorPayment", b =>
                {
                    b.Property<string>("VendorPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("CashRepositoryId")
                        .HasMaxLength(38);

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(38);

                    b.Property<decimal>("PaymentAmount");

                    b.Property<DateTime>("PaymentDate");

                    b.Property<string>("PaymentNumber");

                    b.Property<string>("PaymentTypeId")
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("purchaseOrderId")
                        .HasMaxLength(38);

                    b.HasKey("VendorPaymentId");

                    b.HasIndex("CashRepositoryId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("purchaseOrderId");

                    b.ToTable("VendorPayment");
                });

            modelBuilder.Entity("netcore.Models.Invent.Warehouse", b =>
                {
                    b.Property<string>("warehouseId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("branchId")
                        .HasMaxLength(38);

                    b.Property<string>("city")
                        .HasMaxLength(30);

                    b.Property<string>("country")
                        .HasMaxLength(30);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.Property<string>("province")
                        .HasMaxLength(30);

                    b.Property<string>("street1")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("street2")
                        .HasMaxLength(50);

                    b.Property<string>("warehouseName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("warehouseId");

                    b.HasIndex("branchId");

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("netcore.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("netcore.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("netcore.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("netcore.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("netcore.Models.Invent.CashflowIn", b =>
                {
                    b.HasOne("netcore.Models.Invent.CashRepository", "CashRepositoryFrom")
                        .WithMany()
                        .HasForeignKey("CashRepositoryFromCashRepositoryId");

                    b.HasOne("netcore.Models.Invent.CashRepository", "CashRepositoryTo")
                        .WithMany()
                        .HasForeignKey("CashRepositoryToCashRepositoryId");

                    b.HasOne("netcore.Models.Invent.MoneyTransferOrder", "MoneyTransferOrder")
                        .WithMany()
                        .HasForeignKey("MoneyTransferOrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("netcore.Models.Invent.CashflowOut", b =>
                {
                    b.HasOne("netcore.Models.Invent.CashRepository", "CashRepositoryFrom")
                        .WithMany()
                        .HasForeignKey("CashRepositoryFromCashRepositoryId");

                    b.HasOne("netcore.Models.Invent.CashRepository", "CashRepositoryTo")
                        .WithMany()
                        .HasForeignKey("CashRepositoryToCashRepositoryId");

                    b.HasOne("netcore.Models.Invent.MoneyTransferOrder", "MoneyTransferOrder")
                        .WithMany()
                        .HasForeignKey("MoneyTransferOrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("netcore.Models.Invent.CashRepository", b =>
                {
                    b.HasOne("netcore.Models.Invent.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("netcore.Models.Invent.Catalog", b =>
                {
                    b.HasOne("netcore.Models.Invent.Customer", "Customer")
                        .WithMany("Catalog")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("netcore.Models.Invent.CatalogLine", b =>
                {
                    b.HasOne("netcore.Models.Invent.Catalog", "Catalog")
                        .WithMany("CatalogLine")
                        .HasForeignKey("CatalogId");

                    b.HasOne("netcore.Models.Invent.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("netcore.Models.Invent.Category", b =>
                {
                    b.HasOne("netcore.Models.Invent.Category", "ParentCategory")
                        .WithMany("Categories")
                        .HasForeignKey("ParentCategoryID");
                });

            modelBuilder.Entity("netcore.Models.Invent.Customer", b =>
                {
                    b.HasOne("netcore.Models.Invent.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("netcore.Models.Invent.CustomerLine", b =>
                {
                    b.HasOne("netcore.Models.Invent.Customer", "customer")
                        .WithMany("CustomerLine")
                        .HasForeignKey("customerId");
                });

            modelBuilder.Entity("netcore.Models.Invent.EmployeePayment", b =>
                {
                    b.HasOne("netcore.Models.Invent.CashRepository", "CashRepository")
                        .WithMany("EmployeePayment")
                        .HasForeignKey("CashRepositoryId");

                    b.HasOne("netcore.Models.Invent.Employee", "Employee")
                        .WithMany("EmployeePayment")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("netcore.Models.Invent.PaymentType", "paymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeId");
                });

            modelBuilder.Entity("netcore.Models.Invent.Invoice", b =>
                {
                    b.HasOne("netcore.Models.Invent.Shipment", "Shipment")
                        .WithMany("invoice")
                        .HasForeignKey("shipmentId");
                });

            modelBuilder.Entity("netcore.Models.Invent.InvoiceLine", b =>
                {
                    b.HasOne("netcore.Models.Invent.Invoice", "Invoice")
                        .WithMany("InvoiceLine")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("netcore.Models.Invent.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("netcore.Models.Invent.MoneyTransferOrder", b =>
                {
                    b.HasOne("netcore.Models.Invent.CashRepository", "CashRepositoryFrom")
                        .WithMany()
                        .HasForeignKey("CashRepositoryFromCashRepositoryId");

                    b.HasOne("netcore.Models.Invent.CashRepository", "CashRepositoryTo")
                        .WithMany()
                        .HasForeignKey("CashRepositoryToCashRepositoryId");
                });

            modelBuilder.Entity("netcore.Models.Invent.PaymentReceive", b =>
                {
                    b.HasOne("netcore.Models.Invent.CashRepository", "CashRepository")
                        .WithMany("paymentReceive")
                        .HasForeignKey("CashRepositoryId");

                    b.HasOne("netcore.Models.Invent.Employee", "Employee")
                        .WithMany("PaymentReceive")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("netcore.Models.Invent.Invoice", "invoice")
                        .WithMany("PaymentReceive")
                        .HasForeignKey("InvoiceId");

                    b.HasOne("netcore.Models.Invent.PaymentType", "paymentType")
                        .WithMany("PaymentReceive")
                        .HasForeignKey("PaymentTypeId");
                });

            modelBuilder.Entity("netcore.Models.Invent.ProductLine", b =>
                {
                    b.HasOne("netcore.Models.Invent.Product", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId");

                    b.HasOne("netcore.Models.Invent.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("netcore.Models.Invent.PurchaseOrder", b =>
                {
                    b.HasOne("netcore.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("netcore.Models.Invent.Vendor", "vendor")
                        .WithMany()
                        .HasForeignKey("vendorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("netcore.Models.Invent.PurchaseOrderLine", b =>
                {
                    b.HasOne("netcore.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId");

                    b.HasOne("netcore.Models.Invent.PurchaseOrder", "purchaseOrder")
                        .WithMany("purchaseOrderLine")
                        .HasForeignKey("purchaseOrderId");
                });

            modelBuilder.Entity("netcore.Models.Invent.Receiving", b =>
                {
                    b.HasOne("netcore.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId");

                    b.HasOne("netcore.Models.Invent.PurchaseOrder", "purchaseOrder")
                        .WithMany()
                        .HasForeignKey("purchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("netcore.Models.Invent.Vendor", "vendor")
                        .WithMany()
                        .HasForeignKey("vendorId");

                    b.HasOne("netcore.Models.Invent.Warehouse", "warehouse")
                        .WithMany()
                        .HasForeignKey("warehouseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("netcore.Models.Invent.ReceivingLine", b =>
                {
                    b.HasOne("netcore.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId");

                    b.HasOne("netcore.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId");

                    b.HasOne("netcore.Models.Invent.Receiving", "receiving")
                        .WithMany("receivingLine")
                        .HasForeignKey("receivingId");

                    b.HasOne("netcore.Models.Invent.Warehouse", "warehouse")
                        .WithMany()
                        .HasForeignKey("warehouseId");
                });

            modelBuilder.Entity("netcore.Models.Invent.SalesOrder", b =>
                {
                    b.HasOne("netcore.Models.Invent.Employee", "Employee")
                        .WithMany("SalesOrder")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("netcore.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("netcore.Models.Invent.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("customerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("netcore.Models.Invent.CustomerLine", "customerLine")
                        .WithMany()
                        .HasForeignKey("customerLineId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("netcore.Models.Invent.SalesOrderLine", b =>
                {
                    b.HasOne("netcore.Models.Invent.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("netcore.Models.Invent.SalesOrder", "SalesOrder")
                        .WithMany("salesOrderLine")
                        .HasForeignKey("SalesOrderId");
                });

            modelBuilder.Entity("netcore.Models.Invent.Shipment", b =>
                {
                    b.HasOne("netcore.Models.Invent.Employee", "Employee")
                        .WithMany("Shipment")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("netcore.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId");

                    b.HasOne("netcore.Models.Invent.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("customerId");

                    b.HasOne("netcore.Models.Invent.SalesOrder", "salesOrder")
                        .WithMany()
                        .HasForeignKey("salesOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("netcore.Models.Invent.Warehouse", "warehouse")
                        .WithMany()
                        .HasForeignKey("warehouseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("netcore.Models.Invent.ShipmentLine", b =>
                {
                    b.HasOne("netcore.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId");

                    b.HasOne("netcore.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId");

                    b.HasOne("netcore.Models.Invent.Shipment", "shipment")
                        .WithMany("shipmentLine")
                        .HasForeignKey("shipmentId");

                    b.HasOne("netcore.Models.Invent.Warehouse", "warehouse")
                        .WithMany()
                        .HasForeignKey("warehouseId");
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferIn", b =>
                {
                    b.HasOne("netcore.Models.Invent.Branch", "branchFrom")
                        .WithMany()
                        .HasForeignKey("branchFrombranchId");

                    b.HasOne("netcore.Models.Invent.Branch", "branchTo")
                        .WithMany()
                        .HasForeignKey("branchTobranchId");

                    b.HasOne("netcore.Models.Invent.TransferOrder", "transferOrder")
                        .WithMany()
                        .HasForeignKey("transferOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("netcore.Models.Invent.Warehouse", "warehouseFrom")
                        .WithMany()
                        .HasForeignKey("warehouseFromwarehouseId");

                    b.HasOne("netcore.Models.Invent.Warehouse", "warehouseTo")
                        .WithMany()
                        .HasForeignKey("warehouseTowarehouseId");
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferInLine", b =>
                {
                    b.HasOne("netcore.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId");

                    b.HasOne("netcore.Models.Invent.TransferIn", "transferIn")
                        .WithMany("transferInLine")
                        .HasForeignKey("transferInId");
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferOrder", b =>
                {
                    b.HasOne("netcore.Models.Invent.Branch", "branchFrom")
                        .WithMany()
                        .HasForeignKey("branchFrombranchId");

                    b.HasOne("netcore.Models.Invent.Branch", "branchTo")
                        .WithMany()
                        .HasForeignKey("branchTobranchId");

                    b.HasOne("netcore.Models.Invent.Warehouse", "warehouseFrom")
                        .WithMany()
                        .HasForeignKey("warehouseFromwarehouseId");

                    b.HasOne("netcore.Models.Invent.Warehouse", "warehouseTo")
                        .WithMany()
                        .HasForeignKey("warehouseTowarehouseId");
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferOrderLine", b =>
                {
                    b.HasOne("netcore.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId");

                    b.HasOne("netcore.Models.Invent.TransferOrder", "transferOrder")
                        .WithMany("transferOrderLine")
                        .HasForeignKey("transferOrderId");
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferOut", b =>
                {
                    b.HasOne("netcore.Models.Invent.Branch", "branchFrom")
                        .WithMany()
                        .HasForeignKey("branchFrombranchId");

                    b.HasOne("netcore.Models.Invent.Branch", "branchTo")
                        .WithMany()
                        .HasForeignKey("branchTobranchId");

                    b.HasOne("netcore.Models.Invent.TransferOrder", "transferOrder")
                        .WithMany()
                        .HasForeignKey("transferOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("netcore.Models.Invent.Warehouse", "warehouseFrom")
                        .WithMany()
                        .HasForeignKey("warehouseFromwarehouseId");

                    b.HasOne("netcore.Models.Invent.Warehouse", "warehouseTo")
                        .WithMany()
                        .HasForeignKey("warehouseTowarehouseId");
                });

            modelBuilder.Entity("netcore.Models.Invent.TransferOutLine", b =>
                {
                    b.HasOne("netcore.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId");

                    b.HasOne("netcore.Models.Invent.TransferOut", "transferOut")
                        .WithMany("transferOutLine")
                        .HasForeignKey("transferOutId");
                });

            modelBuilder.Entity("netcore.Models.Invent.VendorCatalog", b =>
                {
                    b.HasOne("netcore.Models.Invent.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("netcore.Models.Invent.VendorCatalogLine", b =>
                {
                    b.HasOne("netcore.Models.Invent.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("netcore.Models.Invent.VendorCatalog", "VendorCatalog")
                        .WithMany("VendorCatalogLine")
                        .HasForeignKey("VendorCatalogId");
                });

            modelBuilder.Entity("netcore.Models.Invent.VendorLine", b =>
                {
                    b.HasOne("netcore.Models.Invent.Vendor", "vendor")
                        .WithMany("vendorLine")
                        .HasForeignKey("vendorId");
                });

            modelBuilder.Entity("netcore.Models.Invent.VendorPayment", b =>
                {
                    b.HasOne("netcore.Models.Invent.CashRepository", "CashRepository")
                        .WithMany()
                        .HasForeignKey("CashRepositoryId");

                    b.HasOne("netcore.Models.Invent.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("netcore.Models.Invent.PaymentType", "paymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeId");

                    b.HasOne("netcore.Models.Invent.PurchaseOrder", "purchaseOrder")
                        .WithMany("vendorPayment")
                        .HasForeignKey("purchaseOrderId");
                });

            modelBuilder.Entity("netcore.Models.Invent.Warehouse", b =>
                {
                    b.HasOne("netcore.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId");
                });
#pragma warning restore 612, 618
        }
    }
}
